import numpy as np
def join_1d_np():
    print("Concetante 1-D Arrays")
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])
    print("First Array")
    print(arr1)
    print("second Array")
    print(arr2)
    arr = np.concatenate((arr1, arr2))
    print("Array after concetenate")
    print(arr)

def join_2d_np():
    print("Concetante 2-D Arrays")
    arr1 = np.array([[1, 2], [3, 4]])
    arr2 = np.array([[5, 6], [7, 8]])
    print("First Array")
    print(arr1)
    print("second Array")
    print(arr2)
    arr = np.concatenate((arr1, arr2), axis=1)
    print("Array after concetenate")
    print(arr)

def stack_np():
    print("Concetante stack method")
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])
    print("First Array")
    print(arr1)
    print("second Array")
    print(arr2)
    arr = np.stack((arr1, arr2), axis=1)
    print("Array after concetenate")
    print(arr)

def stack_row_np():
    print("to stack along rows")
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])
    print("First Array")
    print(arr1)
    print("second Array")
    print(arr2)
    arr = np.hstack((arr1, arr2))
    print("Array after concetenate")
    print(arr)

def stack_colmn_np():
    print("to stack along columns")
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])
    print("First Array")
    print(arr1)
    print("second Array")
    print(arr2)
    arr = np.vstack((arr1, arr2))
    print("Array after concetenate")
    print(arr)

def stack_height_np():
    print("to stack along height")
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])
    print("First Array")
    print(arr1)
    print("second Array")
    print(arr2)
    arr = np.dstack((arr1, arr2))
    print("Array after concetenate")
    print(arr)

if __name__ == "__main__":
    join_1d_np()
    print("\n")
    join_2d_np()
    print("\n")
    stack_np()
    print("\n")
    stack_row_np()
    print("\n")
    stack_colmn_np()
    print("\n")
    stack_height_np